# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: friday-hacks

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    environment:
      WEATHER: "cloudy"
    events:
      - http:
          path: hello-world
          method: get
          cors: true

  helloMars:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    environment:
      WEATHER: "sunny"
    events:
      - http:
          path: hello-mars
          method: get
          cors: true
